package constants

// Client Constants.
const (
	SCREEN_HEIGHT     = 360
	SCREEN_WIDTH      = 640
	MAX_TICKS         = 1200000
	SCENE_CACHE_LIMIT = 5

	IMAGE_EXTENSION = ".png"
	ASSET_ROOT_PATH = "./assets/"

	SCENE_ASSETS_SUB_PATH     = "scenes/"     // ./assets/scenes/
	UI_ASSETS_SUB_PATH        = "UI/"         // ./assets/UI/
	CHARACTER_ASSETS_SUB_PATH = "characters/" // ./assets/characters/

	PLAYER_ASSETS_SUB_PATH     = CHARACTER_ASSETS_SUB_PATH + "player/" // ./assets/characters/player/
	CHAT_SCENE_ASSETS_SUB_PATH = "chats/"                              // ./assets/scenes/SCENE_SECTION/SCENE_NAME/chat/
)

// Player  Constants.

const (
	// RIGID BODY.
	PLAYER_WIDTH           = 18
	PLAYER_HEIGHT          = 55
	PLAYER_SPRITE_OFFSET_X = 70
	PLAYER_SPRITE_OFFSET_Y = 100

	// ANIMATIONS.
	PLAYER_IDLE_ANIM_SPEED = 20
	PLAYER_RUN_ANIM_SPEED  = 12
	PLAYER_JUMP_ANIM_SPEED = 8
	PLAYER_FALL_ANIM_SPEED = 12

	PLAYER_IDLE_FRAME_COUNT = 7
	PLAYER_RUN_FRAME_COUNT  = 8
	PLAYER_JUMP_FRAME_COUNT = 5
	PLAYER_FALL_FRAME_COUNT = 2

	PLAYER_ANIMATIONS_SPRITE_WIDTH  = 144
	PLAYER_ANIMATIONS_SPRITE_HEIGHT = 126

	// ANIM STATES.
	PLAYER_ANIM_STATE_IDLE = "idle"
	PLAYER_ANIM_STATE_RUN  = "run"
	PLAYER_ANIM_STATE_JUMP = "jump"
	PLAYER_ANIM_STATE_FALL = "fall"
)

// Camera Constants.
const (
	CAMERA_MIN_SPEED = 2.5
	CAMERA_MAX_SPEED = 3.5
	CAMERA_EPSILON   = SCREEN_WIDTH/2 - 270
)

// Chat Constants.
const (
	CHAT_FRAME_WIDTH       = SCREEN_WIDTH - 21
	CHAT_ANIM_POP_UP_SPEED = 12
	CHAT_ANIM_TEXT_SPEED   = 12
	CHAT_POP_UP_TICKS      = 2 * CHAT_ANIM_POP_UP_SPEED
	CHAT_MAP_SLIDES_KEY    = "slides"
	CHAT_MAP_PORTRAITS_KEY = "portraits"

	CHAT_STATE_POP_UP   = "chatPopUp"
	CHAT_STATE_POP_DOWN = "chatPopDown"
)
